# utils/recommender.py
# Contains all recommendation logic: scoring, filtering, and related projects.
# Kept separate from routing so it can be tested and extended independently.

import json
import os

from utils.data_loader import load_all_projects

# Maximum number of recommendations returned to the user
MAX_RESULTS = 3

# Maximum number of "you might also like" projects returned alongside results
MAX_RELATED = 3

# Scoring weights used by the recommendation engine.
# Higher weights mean that criterion has more influence
# on the final recommendation score.
SCORING_WEIGHTS = {
    "skill":    3,
    "level":    2,
    "interest": 2,
    "time":     1,
}

# Common aliases and abbreviations for skills.
# This improves recommendation accuracy by normalizing user input.
SKILL_ALIASES = {
    "js":      "javascript",
    "py":      "python",
    "html5":   "html",
    "css3":    "css",
    "c++":     "cpp",
    "web dev": "javascript",
}

# Path to the precomputed cluster assignments.
# Generated by: python scripts/cluster_projects.py
_CLUSTERS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "clusters.json",
)


# ---------------------------------------------------------------------------
# Skill parsing
# ---------------------------------------------------------------------------

def parse_skills(skills_string):
    """
    Convert a raw comma-separated skills string into
    a normalized lowercase list.

    Example:
        "JS, HTML5, CSS3" -> ["javascript", "html", "css"]
    """
    raw_skills = [
        s.strip().lower()
        for s in skills_string.split(",")
        if s.strip()
    ]
    return [SKILL_ALIASES.get(skill, skill) for skill in raw_skills]


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def score_single_project(project, user_skills, level, interest, time_availability):
    """
    Calculate a numeric relevance score for one project.

    Scoring rules:
      - Each matching skill:  +3
      - Level match:          +2
      - Interest match:       +2
      - Time match:           +1

    Time filtering: projects that require MORE time than the user has
    available are excluded entirely (score returned as 0).

    Returns an integer score (0 means no match or time mismatch).
    """
    TIME_RANKS = ["low", "medium", "high"]

    user_time    = time_availability.strip().lower()
    project_time = project.get("time", "").strip().lower()

    # If the project needs more time than the user has, exclude it.
    if project_time not in TIME_RANKS or user_time not in TIME_RANKS:
        return 0
    if TIME_RANKS.index(project_time) > TIME_RANKS.index(user_time):
        return 0

    score = 0

    # Skills: count how many of the user's skills the project requires.
    project_skills = [s.lower() for s in project.get("skills", [])]
    matched_skills = sum(1 for skill in user_skills if skill in project_skills)
    score += matched_skills * SCORING_WEIGHTS["skill"]

    if project.get("level", "").lower() == level.lower():
        score += SCORING_WEIGHTS["level"]

    if project.get("interest", "").lower() == interest.lower():
        score += SCORING_WEIGHTS["interest"]

    if project_time == user_time:
        score += SCORING_WEIGHTS["time"]

    return score


# ---------------------------------------------------------------------------
# Clustering helpers
# ---------------------------------------------------------------------------

def _load_clusters():
    """
    Load clusters.json if it exists.

    Returns the parsed dict, or None if the file is missing or unreadable.
    A missing file is a soft failure — the recommender still works,
    it just won't return related projects.
    """
    if not os.path.exists(_CLUSTERS_PATH):
        return None
    try:
        with open(_CLUSTERS_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def _get_related(recommended_ids, all_projects, cluster_data):
    """
    Find projects in the same cluster(s) as the recommended projects,
    excluding the ones already recommended.

    Returns up to MAX_RELATED project dicts.
    """
    clusters = cluster_data.get("clusters", {})  # {str(pid): cid}
    members  = cluster_data.get("members",  {})  # {str(cid): [pid, ...]}

    # Collect which clusters the recommended projects belong to.
    relevant_cluster_ids = set()
    for pid in recommended_ids:
        cid = clusters.get(str(pid))
        if cid is not None:
            relevant_cluster_ids.add(str(cid))

    if not relevant_cluster_ids:
        return []

    # Gather candidate IDs from those clusters, excluding already recommended.
    candidate_ids = []
    for cid in relevant_cluster_ids:
        for pid in members.get(cid, []):
            if pid not in recommended_ids and pid not in candidate_ids:
                candidate_ids.append(pid)

    id_to_project = {p["id"]: p for p in all_projects}
    related = [id_to_project[pid] for pid in candidate_ids if pid in id_to_project]
    return related[:MAX_RELATED]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_recommendations(skills_string, level, interest, time_availability):
    """
    Return the top N recommended projects for the given user inputs,
    along with related projects from the same cluster.

    Return shape:
        {
            "recommendations": [ <project>, ... ],  # up to MAX_RESULTS
            "related":         [ <project>, ... ],  # up to MAX_RELATED
        }

    The "related" list is empty when clusters.json does not exist yet.
    Run scripts/cluster_projects.py to generate it.
    """
    user_skills  = parse_skills(skills_string)
    all_projects = load_all_projects()

    scored = []
    for project in all_projects:
        score = score_single_project(
            project, user_skills, level, interest, time_availability
        )
        if score >= SCORING_WEIGHTS["skill"]:
            scored.append({"project": project, "score": score})

    scored.sort(key=lambda item: item["score"], reverse=True)
    top_projects = [item["project"] for item in scored[:MAX_RESULTS]]
    top_ids      = [p["id"] for p in top_projects]

    cluster_data = _load_clusters()
    related = _get_related(top_ids, all_projects, cluster_data) if cluster_data else []

    return {
        "recommendations": top_projects,
        "related":         related,
    }


def validate_recommendation_inputs(skills, level, interest, time_availability):
    """
    Validate all four required fields.
    Returns a list of error strings. An empty list means all inputs are valid.
    """
    errors = []

    if not skills or not skills.strip():
        errors.append("Please enter at least one skill.")

    if not level or not level.strip():
        errors.append("Please select an experience level.")

    if not interest or not interest.strip():
        errors.append("Please select an area of interest.")

    if not time_availability or not time_availability.strip():
        errors.append("Please select your time availability.")

    return errors